#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Tasuku43\CodeGenerator\Console\Command\GenerateCommand;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('Code generator', '0.1.0');

$app->add(new GenerateCommand());

$app->run();
